name: thermocode
dependencies:
- ecdsa=0.11=py27_0
- fabric=1.10.2=py27_0
- ipython=3.2.1=py27_0
- markdown=2.6.2=py27_0
- openssl=1.0.1k=1
- paramiko=1.15.2=py27_0
- pip=7.1.0=py27_1
- pycrypto=2.6.1=py27_0
- python=2.7.10=0
- python.app=1.2=py27_4
- readline=6.2=2
- setuptools=18.1=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.24.0=py27_0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - blinker==1.4
  - docutils==0.12
  - feedgenerator==1.7
  - jinja2==2.8
  - markupsafe==0.23
  - pelican==3.6.3
  - pygments==2.0.2
  - python-dateutil==2.4.2
  - pytz==2015.4
  - six==1.9.0
  - smartypants==1.8.6
  - typogrify==2.0.7
  - unidecode==0.4.18
